apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- contour-deployment.yaml

patches:
- path: service-patch.yaml

{% if repo_mirror is defined %}
images:
- name: ghcr.io/projectcontour/contour:v1.28.3
  newName: {{ repo_mirror }}/ghcr.io/projectcontour/contour
  newTag: v1.28.3
- name: ghcr.io/projectcontour/contour:v1.28.3
  newName: {{ repo_mirror }}/ghcr.io/projectcontour/contour
  newTag: v1.28.3
- name: docker.io/envoyproxy/envoy:v1.29.3
  newName: {{ repo_mirror }}/docker.io/envoyproxy/envoy
  newTag: v1.29.3
- name: ghcr.io/projectcontour/contour:v1.28.3
  newName: {{ repo_mirror }}/ghcr.io/projectcontour/contour
  newTag: v1.28.3
- name: ghcr.io/projectcontour/contour:v1.28.3
  newName: {{ repo_mirror }}/ghcr.io/projectcontour/contour
  newTag: v1.28.3
{% endif %}
