- name: Read service definitions from services.yml
  hosts: "*, localhost"
  tasks:
    - name: Include basic system definitions from system_vars.yaml
      ansible.builtin.include_vars:
        file: system_vars.yml
    - name: Include service defnitions from services_vars.yaml
      ansible.builtin.include_vars:
        file: services_vars.yml

- name: Common setup
  hosts: loadbalancer, master, worker
  roles:
    - common

# If you don't want an explicit loadbalancer, simpler comment out this part of the playbook
# and declare the hosts here to master.
# In this case there's a loadbalancer on every master
- name: Rollout loadbalancer
  hosts: master, worker
  roles:
    - loadbalancer

- name: Install master and workers
  hosts: master, worker
  roles:
    - prereq
    - kubernetes
    - k8s_components
    - postinstall
