{% if repo_mirror is defined %}
images:
- name: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0
  newName: {{ repo_mirror }}/registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.15.0
- name: quay.io/prometheus/blackbox-exporter:v0.26.0
  newName: {{ repo_mirror }}/quay.io/prometheus/blackbox-exporter
  newTag: v0.26.0
- name: quay.io/prometheus/pushgateway:v1.11.1
  newName: {{ repo_mirror }}/quay.io/prometheus/pushgateway
  newTag: v1.11.1
- name: quay.io/prometheus-operator/prometheus-config-reloader:v0.83.0
  newName: {{ repo_mirror }}/quay.io/prometheus-operator/prometheus-config-reloader
  newTag: v0.83.0
- name: quay.io/prometheus/prometheus:v3.4.1
  newName: {{ repo_mirror }}/quay.io/prometheus/prometheus
  newTag: v3.4.1
- name: quay.io/prometheus/alertmanager:v0.28.1
  newName: {{ repo_mirror }}/quay.io/prometheus/alertmanager
  newTag: v0.28.1
- name: quay.io/prometheus/node-exporter:v1.9.1
  newName: {{ repo_mirror }}/quay.io/prometheus/node-exporter
  newTag: v1.9.1
{% endif %}
