apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- template.yaml
- blackbox-template.yaml

namespace: monitoring

patches:
# path in prometheus-server Deployment:
# - add additional option to read web-config
# - mount web-certs in container
# - patch liveness and readiness to use HTTPS and auth
# - patch reloader-sidecar reload-url
- target:
    kind: Deployment
    name: g8s-prometheus-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/1/volumeMounts/-
      value:
        mountPath: /etc/prometheus/blackbox-targets.yml
        name: blackbox-targets
        subPath: blackbox-targets.yml
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: blackbox-targets
        configMap:
          defaultMode: 420
          name: prometheus-blackbox-targets

configMapGenerator:
  - name: prometheus-blackbox-targets
    files:
    - blackbox-targets.yml

generatorOptions:
  disableNameSuffixHash: true

{% if repo_mirror is defined %}
images:
- name: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0
  newName: {{ repo_mirror }}/registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.15.0
- name: quay.io/prometheus/blackbox-exporter:v0.26.0
  newName: {{ repo_mirror }}/quay.io/prometheus/blackbox-exporter
  newTag: v0.26.0
- name: quay.io/prometheus/pushgateway:v1.11.1
  newName: {{ repo_mirror }}/quay.io/prometheus/pushgateway
  newTag: v1.11.1
- name: quay.io/prometheus-operator/prometheus-config-reloader:v0.83.0
  newName: {{ repo_mirror }}/quay.io/prometheus-operator/prometheus-config-reloader
  newTag: v0.83.0
- name: quay.io/prometheus/prometheus:v3.4.1
  newName: {{ repo_mirror }}/quay.io/prometheus/prometheus
  newTag: v3.4.1
- name: quay.io/prometheus/alertmanager:v0.28.1
  newName: {{ repo_mirror }}/quay.io/prometheus/alertmanager
  newTag: v0.28.1
- name: quay.io/prometheus/node-exporter:v1.9.1
  newName: {{ repo_mirror }}/quay.io/prometheus/node-exporter
  newTag: v1.9.1
{% endif %}
