{% if repo_mirror is defined %}
images:
- name: registry.k8s.io/metrics-server/metrics-server:v0.7.2
  newName: {{ repo_mirror }}/registry.k8s.io/metrics-server/metrics-server
  newTag: v0.7.2
{% endif %}
