apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- components.yaml
- sa.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- secret.yaml

patches:
  - target:
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls

{% if repo_mirror is defined %}
images:
- name: registry.k8s.io/metrics-server/metrics-server:v0.7.2
  newName: {{ repo_mirror }}/registry.k8s.io/metrics-server/metrics-server
  newTag: v0.7.2
{% endif %}
