
- name: Create component dir for {{ component }}
  ansible.builtin.file:
    path: "/opt/kubernetes/components/{{ component }}"
    state: directory
    mode: '0755'

- name: Generate configs for {{ component }}
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/opt/kubernetes/components/{{ component }}"
  with_fileglob: "components/{{ component }}/*"

- name: Is there an install.sh? 
  ansible.builtin.stat:
    path: "/opt/kubernetes/components/{{ component }}/install.sh"
  register: install_sh
  when: groups.master[0] in inventory_hostname

- name: Install via install.sh
  ansible.builtin.command:
    chdir: "/opt/kubernetes/components/{{ component }}"
    cmd: "sh ./install.sh"
  when: (groups.master[0] in inventory_hostname) and (install_sh.stat.exists)

- name: Else install via kustomize 
  ansible.builtin.command:
    chdir: "/opt/kubernetes/components/{{ component }}"
    cmd: "kubectl apply -k ."
  when: (groups.master[0] in inventory_hostname) and (not install_sh.stat.exists)