- name: Create a directory for local-storage
  ansible.builtin.file:
    path: /opt/kubernetes/config/local-storage
    state: directory
    mode: '0755'

- name: Generate local-storage config on first master
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/kubernetes/config/local-storage/
  with_fileglob: ../templates/local-storage/*
  register: localstorage_files

- name: Install local-storage with kustomize
  ansible.builtin.command:
    cmd: kubectl apply -k /opt/kubernetes/config/local-storage/
  when: localstorage_files is changed

- name: Create a directory for persistences (/data/k8s/)
  ansible.builtin.file:
    path: /data/k8s
    state: directory
    mode: '0755'
  register: create_data_k8s

- name: Set selinux context for persistences
  ansible.builtin.shell: |
    semanage fcontext -a -t container_file_t  "/data/k8s(/.*)?"
    restorecon -R /data/k8s