- name: Define api_host
  ansible.builtin.set_fact:
    api_host: >-
      {% if groups.loadbalancer[0] is defined -%}
        {{ groups.loadbalancer[0] }}
      {%- else -%}
        {% if api_loadbalancer is defined -%}
          {{ api_loadbalancer }}
        {%- else -%}
          {{ groups.master[0] }}
        {%- endif %}
      {%- endif %}
- name: Define control_plane
  ansible.builtin.set_fact:
    control_plane: >-
      {% if api_loadbalancer_port is defined -%}
        {{ api_host }}:{{ api_loadbalancer_port }}
      {%- else -%}
        {{ api_host }}:{{ lb_api_port }}
      {%- endif %}

- name: Install taint-master.sh in /usr/local/sbin/taint-master.sh
  ansible.builtin.copy:
    src: roles/k8s_components/files/sbin/taint-master.sh
    dest: /usr/local/sbin/taint-master.sh
    owner: root
    group: root
    mode: 0o755

- name: Make ServiceAccount for customer
  ansible.builtin.include_tasks: customeruser.yml
  when: groups.master[0] in inventory_hostname

- name: Generate customer config on all masters
  ansible.builtin.include_tasks: customer-config.yml
  when: inventory_hostname in groups["master"]

- name: Get components
  ansible.builtin.find:
    paths: components
    recurse: no
    file_type: directory
    excludes: "*.disabled"
  delegate_to: localhost
  register: components_list

- name: Execute subtask for components
  ansible.builtin.include_tasks: components.yml
  loop: "{{ components_list.files }}"
  loop_control:
    loop_var: component
  when: inventory_hostname in groups["master"]