- name: Create a directory for metrics-server
  ansible.builtin.file:
    path: /opt/kubernetes/config/metrics-server
    state: directory
    mode: '0755'

- name: Generate metrics-server config on first master
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/kubernetes/config/metrics-server/
  with_fileglob: ../templates/metrics-server/*
  register: metricsserver_files

- name: Install metrics-server with kustomize
  ansible.builtin.command:
    cmd: kubectl apply -k /opt/kubernetes/config/metrics-server/
  when: metricsserver_files is changed

- name: Copy get-metrics-server-token.sh script to /usr/local/sbin
  ansible.builtin.copy:
    src: roles/k8s_components/files/sbin/get-metrics-reader-token.sh
    dest: /usr/local/sbin/get-metrics-reader-token.sh
    owner: root
    group: root
    mode: 0o700
  when: (inventory_hostname in groups["master"]) and (metricsserver_files is changed)