{% if image_mirror is defined %}
images:
- name: quay.io/jetstack/cert-manager-controller:v1.14.4
  newName: {{ image_mirror }}/quay.io/jetstack/cert-manager-controller
  newTag: v1.14.4
- name: quay.io/jetstack/cert-manager-cainjector:v1.14.4
  newName: {{ image_mirror }}/quay.io/jetstack/cert-manager-cainjector
  newTag: v1.14.4
- name: quay.io/jetstack/cert-manager-webhook:v1.14.4
  newName: {{ image_mirror }}/quay.io/jetstack/cert-manager-webhook
  newTag: v1.14.4
{% endif %}
