- name: Generate token and join on first master for worker
  ansible.builtin.shell:
    cmd: echo $(KUBECONFIG=/etc/kubernetes/admin.conf kubeadm token create --print-join-command)
  register: join_content
  delegate_to: "{{ groups.master[0] }}"
  changed_when: false


- name: Execute join command on worker
  ansible.builtin.shell:
    cmd: "KUBECONFIG=/etc/kubernetes/admin.conf {{ join_content.stdout }}"
    creates: /etc/kubernetes/kubelet.conf
  when: join_content is defined
