apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
  - nonResourceURLs:
    - "/metrics"
    - "/metrics/*"
    verbs:
    - get
    - list
    - watch
