apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- components.yaml
- sa.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- secret.yaml

patches:
  - target:
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls

