- name: Drain node
  ansible.builtin.command:
    cmd: "kubectl drain {{ ansible_fqdn }} --force --ignore-daemonsets --delete-emptydir-data"
  delegate_to: "{{ groups.master[0] }}"
  ignore_errors: true

- name: "Install new version of kubectl, kubelet and cri-o"
  ansible.builtin.yum:
    name:
    - kubelet-{{ k8s_version }}
    - kubectl-{{ k8s_version }}
    - cri-o-{{ crio_version }}
    disable_excludes: all
    state: present

- name: Restart kubelet
  ansible.builtin.systemd:
    state: restarted
    name: kubelet

- name: Restart cri-o
  ansible.builtin.systemd:
    state: restarted
    name: cri-o

- name: Wait for sure until node is ready again (3 minutes)
  ansible.builtin.pause:
    minutes: 3

- name: Uncordon node
  ansible.builtin.command:
    cmd: "kubectl uncordon {{ ansible_fqdn }}"
  delegate_to: "{{ groups.master[0] }}"
