- name: Delete old repo definitions if they are there
  ansible.builtin.file:
    path: /etc/yum.repos.d/libcontainers.repo
    state: absent
  ignore_errors: true

- name: Copy cri-o repo definitions in place
  ansible.builtin.template:
    src: roles/upgrade_cluster/templates/crio.repo.j2
    dest: /etc/yum.repos.d/crio.repo

- name: Copy kubernetes repo definitions in place
  ansible.builtin.template:
    src: roles/upgrade_cluster/templates/kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: "Install or check for existence of some required tools"
  ansible.builtin.yum:
    name:
      - containernetworking-plugins
      - socat
      - conntrack-tools
      - container-selinux
      - tar 
      - git
      - kubernetes-cni
    disable_excludes: all
    state: latest

- name: "Install kubeadm-{{ k8s_version }}"
  ansible.builtin.yum:
    name:
      - kubeadm-{{ k8s_version }}
    disable_excludes: all
    state: present
