kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: httpbin-s
  annotations:
    cert-manager.io/cluster-issuer: gubernat-issuer
spec:
  ingressClassName: contour
  tls:
    - hosts:
        # This funny contruct generates a clustername from ansible (look in /etc/hosts ;-))
        - {{ ansible_fqdn | regex_replace('^([\\d\\w]+)-[\\d\\w]+\\.', '\\1.') }}
      secretName: httpbin-tls-secret
  rules:
    - host: {{ ansible_fqdn | regex_replace('^([\\d\\w]+)-[\\d\\w]+\\.', '\\1.') }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: httpbin
                port:
                  number: 80