apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gubernat-tests-dev

resources:
- namespace.yaml
- deployment.yaml
- ingress-https.yaml
- ingress.yaml
- svc.yaml

{% if repo_mirror is defined %}
images:
- name: docker.io/kennethreitz/httpbin
  newName: {{ repo_mirror }}/docker.io/kennethreitz/httpbin
  newTag: latest
{% endif %}
