apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gubernat-tests-dev

resources:
- namespace.yaml
- deployment.yaml
- ingress-https.yaml
- ingress.yaml
- svc.yaml

{% if repo_mirror is defined %}
images:
- name: ghcr.io/psf/httpbin
  newName: {{ repo_mirror }}/ghcr.io/psf/httpbin
  newTag: 0.10.2
{% endif %}
