apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- daemonset.yaml
- service.yaml

namespace: opentelemetry

configMapGenerator:
  - name: otel-collector-config
    files:
      - config.yaml=collector-config.yaml

{% if image_mirror is defined %}
images:
- name: otel/opentelemetry-collector-contrib:0.51.0
  newName: {{ image_mirror }}/docker.io/otel/opentelemetry-collector-contrib
  newTag: 0.51.0
{% endif %}
