apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- daemonset.yaml
- service.yaml

namespace: opentelemetry

configMapGenerator:
  - name: otel-collector-config
    files:
      - config.yaml=collector-config.yaml

generatorOptions:
  disableNameSuffixHash: true

{% if repo_mirror is defined %}
images:
- name: otel/opentelemetry-collector-contrib:0.128.0
  newName: {{ repo_mirror }}/docker.io/otel/opentelemetry-collector-contrib
  newTag: 0.128.0
{% endif %}
