apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- daemonset.yaml
- service.yaml

namespace: opentelemetry

configMapGenerator:
  - name: otel-collector-config
    files:
      - config.yaml=collector-config.yaml
