---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: customer
  name: customer
  namespace: default
type: kubernetes.io/service-account-token