---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customer-node-reader
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: customer-node-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: customer-node-reader
subjects:
- kind: ServiceAccount
  name: customer
  namespace: default