apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-3
spec:
  config: '{
   "cniVersion": "0.3.1",
   "name": "network-3",
   "type": "ipvlan",
   "master": "ens256",
     "ipam": {
        "type": "whereabouts",
        "range": "10.86.2.0/24"
     }
   }'