apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-2
spec:
  config: '{
   "cniVersion": "0.3.1",
   "name": "network-2",
   "type": "ipvlan",
   "master": "ens224",
     "ipam": {
        "type": "whereabouts",
        "range": "10.86.1.0/24"
     }
   }'