apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: network-2, network-3
spec:
  containers:
  - name: test-pod
    image: docker.io/library/alpine:latest
    command: ['sleep', 'infinity']
  terminationGracePeriodSeconds: 0