apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/rancher/local-path-provisioner//deploy?ref=v0.0.23

patchesStrategicMerge:
  - local-path-config-patch.yaml