- name: Define config directory for cluster
  ansible.builtin.set_fact:
    config_dir: "../config:{{ clustername }}"

- name: Make directory for secrets of cluster {{ config_dir }}
  ansible.builtin.file:
    path: "../config:{{ clustername }}"
    state: directory
    mode: u+rwx,g-rwx,o-rwx
  delegate_to: localhost

- name: Generate root ssh key for cluster
  ansible.builtin.shell:
    cmd: "cd {{ config_dir }}; ssh-keygen -t ed25519 -f root-ssh-key -C \"root key for {{ clustername }}\" -q -N \"\" "
    creates: "{{ config_dir }}/root-ssh-key"
  delegate_to: localhost

- name: Generate shell script to copy ssh key to all machines
  ansible.builtin.template:
    src: roles/initialsetup/templates/ssh-copy-id-to-all-hosts.sh.j2
    dest: ../ssh-copy-id-to-all-host.sh
    mode: '0755'
  delegate_to: localhost
